baseURL = 'https://sailingcourage.xyz/'
languageCode = 'en-us'
title = 'Sailing Courage'

theme = "archie"
# copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"

paginate = 5 # articles per page

[params]
# Sections from where to draw posts for main page.
# Otherwise stupidly defaults to section with most posts.
# https://gohugo.io/functions/where/#mainsections
mainSections = [
	'projects',
]
mode = "light" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "DIY projects onboard our 1976 Hallberg-Rassy Rasmus 35 Ketch"
mathjax = false # enable MathJax support
katex = false # enable KaTeX support
customcss = ["css/custom.css"]
goatcounter = "courage" # if set, points to GoatCounter
donationlink = "https://ko-fi.com/sailingcourage"
github = "https://github.com/sailing-courage"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sailing-courage"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/USER/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "other"
url = "/other"
weight = 3

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

# [[menu.main]]
# name = "tags"
# url = "/tags"
# weight = 4
